# Generated by Django 4.1 on 2023-03-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='git',
            field=models.URLField(max_length=900),
        ),
    ]
