# Generated by Django 4.1 on 2023-03-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='git',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
